### ISSUE TITLE
Decimal off in power calculation

### ISSUE THREAD

**Issue by DrTron** [shred/pyquaero#5]
Minor bug, really:

On an aquaero5 Firmware version 2104, the result of the power calculation is off by two decimals. I get:

`"deltaT": 1.12,`
 `"flow": 50.1,`
  `"power": 0.65,`
  `"resistance": 17,`
   `"sensor1": 27.4,`
   `"sensor2": 26.28`

The correct power would be 65W for the flow in L/h and the deltaT in K.
pyquaero 1.3.1 via pip3.

On firmware version 1030, the power calculation is not reported in pyquaero.

**Comment by shred** [comment]
Thank you for the report! Luckily the fix is very easy.

Do you have a way to test it from the github source? Otherwise I would just "risk" a new release with the change. :wink:

**Comment by DrTron** [comment]
No problem.
I can test it tonight by pulling it from github, I'll report back here.
Thanks again for just about the only way to retrieve aquaero data on Linux!

**Comment by shred** [comment]
The pyqtools cannot be run from the directory. `pip` generates a wrapper for them, so you'd need to install pyquaero locally from your clone directory: `pip3 install --user --editable .`

However, I'm quite confident that the fix is working, so I just released a v1.3.2. :wink: You can update the package, and try again.

**Comment by DrTron** [comment]
Interesting that pyqd works directly from the directory, but pyqread does not.
Anyway, I updated it to 1.3.2 via pip and it shows the correct value now:
`"deltaT": 0.8,`
` "flow": 49.4,`
` "power": 45,`
` "resistance": 17,`
` "sensor1": 24.87,`
` "sensor2": 24.07`

Thanks!

**Comment by shred** [comment]
It's really interesting because pyqd also only defines a main function, but has no code that would be executed directly.

Anyway, thank you for the report and your feedback. I'll close this issue.
